services:
  postgres:
    container_name: postgres_db
    image: postgres:alpine
    environment:
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: root
      POSTGRES_DB: parking_control
    ports:
      - 5432:5432

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: admin@diego-garcia.dev
    ports:
      - 5050:80